# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    strategy:
       matrix:
        platform:
          - os: ubuntu-latest
            name: linux
            extension: ""
          - os: windows-latest
            name: windows
            extension: ".exe"
    runs-on: ${{ matrix.platform.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.2'

    - name: Build
      run: go build -o ${{ github.workspace }}/lintex-${{ matrix.platform.name }}-amd64${{ matrix.platform.extension }}

    - name: Test
      run: go test -v ./...
    
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: lintex
        path: ${{ github.workspace }}/lintex-${{ matrix.platform.name }}-amd64${{ matrix.platform.extension }}
