# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.2'

    - name: Build
      run: go build -o ${{ github.workspace }}/lintex-linux-amd64

    - name: Test
      run: go test -v ./...
    
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: lintex-linux-amd64
        path: ${{ github.workspace }}/lintex-linux-amd64
