# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    strategy:
       matrix:
        platform:
          - os: ubuntu-latest
            name: linux
            extension: ""
          - os: windows-latest
            name: windows
            extension: ".exe"
    runs-on: ${{ matrix.platform.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.2'

    - name: Build
      run: go build -o ${{ github.workspace }}/lintex-${{ matrix.platform.name }}-amd64${{ matrix.platform.extension }}

    - name: Test
      run: go test -v ./...
    
    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: lintex-${{ matrix.platform.name }}
        path: ${{ github.workspace }}/lintex-${{ matrix.platform.name }}-amd64${{ matrix.platform.extension }}

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts from build job.
        uses: actions/download-artifact@v4
      - name: Replace latest release
        run: |
          gh release delete latest
          gh release create --prerelease latest lintex-linux/* lintex-windows/*
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
